import React from 'react'
import styles from './page.module.css'
import Image from 'next/image'
import Button from '../../components/button/button'

export default function Contact() {

  
  return (
    <div className={styles.container}>
      <h1 className={styles.title}>Let's Keep in Touch</h1>
      <div className={styles.content}>
        <div className={styles.imgContainer}>
          <Image className={styles.image} src="/contact.png" alt="contact" fill={true} />
        </div>
        <form className={styles.form}>
        <input type='text' placeholder='name'  className={styles.input}></input>
          <input type='text' placeholder='email'  className={styles.input}></input>
          <textarea placeholder='message' cols={30} rows={10}  className={styles.textarea}></textarea>
          <Button url="#" text="Send" />
        </form>
         
      </div>
    </div>
  )
}
export const metadata = {
  title: 'Contact',
  description: 'Generated by create next app',
}

